#!/bin/bash

# Copyright (c) 2022. Uniontech Software Ltd. All rights reserved.
#
# Author:     wurongjie <wurongjie@deepin.org>
#
# Maintainer: wurongjie <wurongjie@deepin.org>
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

module="$1"
arch="$2"

case $module in
    runtime);;
    develop);;
    "") echo "enter an module, like ./create_rootfs.sh runtime amd64" && exit;;
    *) echo "unknow module \"$module\", supported module: runtime, develop" && exit;;
esac


case $arch in
    amd64);;
    arm64);;
    loongarch64);;
    "") echo "enter an architecture, like ./create_rootfs.sh runtime amd64" && exit;;
    *) echo "unknow arch \"$arch\", supported arch: amd64, arm64, loongarch64" && exit;;
esac

runtimePackages=(
acl
at-spi2-common
at-spi2-core
attr
audispd-plugins
auditd
autopoint
bash-builtins
bash-static
bash
binutils-aarch64-linux-gnu
binutils-arc-linux-gnu
binutils-arm-linux-gnueabi
binutils-arm-linux-gnueabihf
binutils-common
binutils-for-build
binutils-for-host
binutils-hppa-linux-gnu
binutils-hppa64-linux-gnu
binutils-i686-gnu
binutils-i686-kfreebsd-gnu
binutils-i686-linux-gnu
binutils-ia64-linux-gnu
binutils-loongarch64-linux-gnu
binutils-m68k-linux-gnu
binutils-multiarch
binutils-powerpc-linux-gnu
binutils-powerpc64-linux-gnu
binutils-powerpc64le-linux-gnu
binutils-riscv64-linux-gnu
binutils-s390x-linux-gnu
binutils-sh4-linux-gnu
binutils-source
binutils-sparc64-linux-gnu
binutils-x86-64-gnu
binutils-x86-64-kfreebsd-gnu
binutils-x86-64-linux-gnu
binutils-x86-64-linux-gnux32
binutils
bluetooth
bluez-cups
bluez-hcidump
bluez-meshd
bluez-obexd
bluez-source
bluez-test-scripts
bluez-test-tools
bluez
bsdextrautils
bsdutils
bzip2
ca-certificates
coreutils
cryptsetup-bin
cryptsetup-initramfs
cryptsetup-ssh
cryptsetup-suspend
cryptsetup
cups-bsd
cups-client
cups-common
cups-core-drivers
cups-daemon
cups-ipp-utils
cups-ppdc
cups-server-common
cups
curl
dbus-bin
dbus-daemon
dbus-session-bus-common
dbus-system-bus-common
dbus-tests
dbus-user-session
dbus-x11
dbus
debuginfod
diffutils
dirmngr
dmeventd
dmsetup
dvb-tools
e2fsck-static
e2fsprogs-l10n
e2fsprogs
eject
elfutils
expat
fdisk
fido2-tools
file
findutils
fontconfig-config
fontconfig
fonts-dejavu-core
fonts-dejavu-extra
fonts-dejavu
freetype2-demos
fuse2fs
gawk
gdbm-l10n
gdbmtool
gdk-pixbuf-tests
gettext-base
gettext-el
gettext
gir1.2-atk-1.0
gir1.2-atspi-2.0
gir1.2-gdkpixbuf-2.0
gir1.2-girepository-3.0
gir1.2-glib-2.0
gir1.2-harfbuzz-0.0
gir1.2-pango-1.0
glib-networking-common
glib-networking-services
glib-networking-tests
glib-networking
glibc-source
glslang-tools
gnupg-agent
gnupg-l10n
gnupg-utils
gnupg2
gnupg
gnutls-bin
gpg-agent
gpg-wks-client
gpg-wks-server
gpg
gpgconf
gpgrt-tools
gpgsm
gpgv-static
gpgv-win32
gpgv2
gpgv
grep
gstreamer1.0-pipewire
guile-gnutls
gzip-win32
gzip
hicolor-icon-theme
icu-devtools
idle-python3.12
idn2
ir-keytable
kbd
kmod
lemon
libacl1
libarchive-tools
libarchive13
libasm1
libasprintf0v5
libassuan0
libatk1.0-0
libatspi2.0-0
libattr1
libaudit-common
libaudit1
libauparse0
libbinutils
libblkid1
libbluetooth3
libbz2-1.0
libc-bin
libc-dev-bin
libc-devtools
libc-l10n
libc6
libcap-ng-utils
libcap-ng0
libcap2-bin
libcap2
libcbor0.8
libcom-err2
libcrypt1
libcryptsetup12
libctf-nobfd0
libctf0
libcups2
libcupsimage2
libcurl3-gnutls
libcurl4
libd3dadapter9-mesa
libdaemon0
libdatrie1-bin
libdatrie1
libdbus-1-3
libdebuginfod-common
libdebuginfod1
libdecor-0-0
libdecor-0-plugin-1-cairo
libdecor-tests
libdevmapper-event1.02.1
libdevmapper1.02.1
libdrm-amdgpu1
libdrm-common
libdrm-intel1
libdrm-nouveau2
libdrm-radeon1
libdrm-tests
libdrm2
libdvbv5-0
libdw1
libegl-mesa0
libegl1
libelf1
libepoxy0
libexpat1
libext2fs2
libfdisk1
libffi8
libfido2-1
libfontconfig1
libfreetype6
libfribidi-bin
libfribidi0
libgbm1
libgcrypt20
libgdbm-compat4
libgdbm6
libgdk-pixbuf-2.0-0
libgdk-pixbuf2.0-bin
libgdk-pixbuf2.0-common
libgettextpo0
libgirepository-2.0-0
libgl1-mesa-dri
libgl1
libglapi-mesa
libgles1
libgles2
libglib2.0-0
libglib2.0-bin
libglib2.0-data
libglib2.0-dev-bin
libglib2.0-tests
libglvnd0
libglx-mesa0
libglx0
libgmp10
libgmpxx4ldbl
libgnutls-dane0
libgnutls-openssl27
libgnutls30
libgnutlsxx30
libgpg-error-l10n
libgpg-error0
libgprofng0
libgraphite2-3
libgraphite2-utils
libharfbuzz-bin
libharfbuzz-cairo0
libharfbuzz-gobject0
libharfbuzz-icu0
libharfbuzz-subset0
libharfbuzz0b
libhogweed6
libice6
libicu73
libicu74
libidn2-0
libjpeg-turbo-progs
libjpeg62-turbo
libkmod2
libksba8
liblcms2-2
liblcms2-utils
liblvm2cmd2.03
liblz4-1
liblz4-tool
liblzma5
libmagic-mgc
libmagic1
libmnl0
libmount1
libncurses5
libncurses6
libncursesw5
libncursesw6
libnettle8
libnghttp2-14
libnspr4
libnss-myhostname
libnss-mymachines
libnss-resolve
libnss-systemd
libnss3-tools
libnss3
libopengl0
libosmesa6
libp11-kit0
libpam-cap
libpam-modules-bin
libpam-modules
libpam-runtime
libpam-systemd
libpam0g
libpango-1.0-0
libpango1.0-0
libpangocairo-1.0-0
libpangoft2-1.0-0
libpangoxft-1.0-0
libpciaccess0
libpcre2-16-0
libpcre2-32-0
libpcre2-8-0
libpcre2-posix3
libpipewire-0.3-0
libpipewire-0.3-common
libpipewire-0.3-modules-x11
libpipewire-0.3-modules
libpixman-1-0
libpng-tools
libpng16-16
libproc2-0
libproxy-tools
libproxy1-plugin-gsettings
libproxy1-plugin-kconfig
libproxy1-plugin-networkmanager
libproxy1-plugin-webkit
libproxy1v5
libpsl5
libpulse-mainloop-glib0
libpulse0
libpulsedsp
libpython3.12-minimal
libpython3.12-stdlib
libpython3.12-testsuite
libpython3.12
libreadline8
libsasl2-2
libsasl2-modules-db
libsasl2-modules-ldap
libsasl2-modules-otp
libsasl2-modules-sql
libsasl2-modules
libseccomp2
libselinux1
libsepol2
libsframe1
libsharpyuv0
libsm6
libsmartcols1
libspa-0.2-bluetooth
libspa-0.2-jack
libspa-0.2-libcamera
libspa-0.2-modules
libsqlite3-0
libsqlite3-tcl
libss2
libssl3
libsubid4
libsystemd-shared
libsystemd0
libtasn1-6
libtasn1-bin
libthai-data
libthai0
libtiff-opengl
libtiff-tools
libtiff6
libtiffxx6
libtinfo5
libtinfo6
libtss2-esys-3.0.2-0
libtss2-fapi1
libtss2-mu0
libtss2-policy0
libtss2-rc0
libtss2-sys1
libtss2-tcti-cmd0
libtss2-tcti-device0
libtss2-tcti-libtpms0
libtss2-tcti-mssim0
libtss2-tcti-pcap0
libtss2-tcti-spi-helper0
libtss2-tcti-swtpm0
libtss2-tctildr0
libturbojpeg-java
libturbojpeg0
libudev1
libunistring2
libuuid1
libv4l-0
libv4l2rds0
libv4lconvert0
libvulkan1
libwayland-bin
libwayland-client0
libwayland-cursor0
libwayland-egl1
libwayland-server0
libwebp7
libwebpdecoder3
libwebpdemux2
libwebpmux3
libwebrtc-audio-processing1
libx11-6
libx11-data
libx11-xcb1
libxatracker2
libxau6
libxcb-composite0
libxcb-cursor0
libxcb-damage0
libxcb-dpms0
libxcb-dri2-0
libxcb-dri3-0
libxcb-ewmh2
libxcb-glx0
libxcb-icccm4
libxcb-image0
libxcb-keysyms1
libxcb-present0
libxcb-randr0
libxcb-record0
libxcb-render-util0
libxcb-render0
libxcb-res0
libxcb-screensaver0
libxcb-shape0
libxcb-shm0
libxcb-sync1
libxcb-util1
libxcb-xf86dri0
libxcb-xfixes0
libxcb-xinerama0
libxcb-xinput0
libxcb-xkb1
libxcb-xtest0
libxcb-xv0
libxcb-xvmc0
libxcb1
libxcomposite1
libxcrypt-source
libxcursor1
libxdamage1
libxdmcp6
libxext6
libxfixes3
libxft2
libxi6
libxinerama1
libxkbcommon-tools
libxkbcommon-x11-0
libxkbcommon0
libxkbfile1
libxkbregistry0
libxml2-utils
libxml2
libxpm4
libxrandr2
libxrender1
libxshmfence1
libxt6
libxtst6
libxv1
libxxf86vm1
libxxhash0
libzstd1
locales-all
locales
locate
login
logsave
lvm2-dbusd
lvm2-lockd
lvm2
lz4
mesa-drm-shim
mesa-opencl-icd
mesa-va-drivers
mesa-vdpau-drivers
mesa-vulkan-drivers
mount
ncurses-base
ncurses-bin
ncurses-examples
ncurses-term
nettle-bin
nghttp2-client
nghttp2-proxy
nghttp2-server
nghttp2
nscd
openssl
p11-kit-modules
p11-kit
pango1.0-tests
pango1.0-tools
passwd
pcre2-utils
perl-base
perl-debug
perl
pipewire-bin
pipewire-jack
pipewire-libcamera
pipewire-pulse
pipewire-tests
pipewire-v4l2
pipewire
procps
psl-make-dafsa
psl
pulseaudio-equalizer
pulseaudio-module-bluetooth
pulseaudio-module-gsettings
pulseaudio-module-jack
pulseaudio-module-lirc
pulseaudio-module-raop
pulseaudio-module-zeroconf
pulseaudio-utils
pulseaudio
python3-audit
python3-cap-ng
python3-graphite2
python3-libproxy
python3-libxml2
python3-seccomp
python3-selinux
python3-xcbgen
python3.12-examples
python3.12-full
python3.12-minimal
python3.12-nopie
python3.12-venv
python3.12
qv4l2
qvidcap
readline-common
rfkill
rlfe
ruby-selinux
sasl2-bin
scdaemon
seccomp
sed
selinux-utils
sepol-utils
shared-mime-info
sqlite3-tools
sqlite3
systemd-boot-efi
systemd-boot
systemd-container
systemd-coredump
systemd-homed
systemd-journal-remote
systemd-oomd
systemd-resolved
systemd-sysv
systemd-tests
systemd-timesyncd
systemd-ukify
systemd-userdbd
systemd
tar-scripts
tar
tzdata-legacy
tzdata
udev
uidmap
unzip
util-linux-extra
util-linux-locales
util-linux
uuid-runtime
v4l-utils
wayland-protocols
webp
x11-xkb-utils
xcb-proto
xdg-user-dirs
xkb-data
xpmutils
xscreensaver-data-extra
xscreensaver-data
xscreensaver-gl-extra
xscreensaver-gl
xscreensaver-screensaver-bsod
xscreensaver-screensaver-webcollage
xscreensaver
xxhash
xz-utils
xzdec
zlib1g
zstd
)

developPackages=("${runtimePackages[@]}")

developPackages+=(
        elfutils
        file
        gcc
        g++
        gdb
        cmake
        xz-utils
        patchelf
)

# 将develop中的lib库添加到runtime，减少两者的差异，避免在develop构建好应用后，无法在runtime运行的问题
while IFS= read -r line; do
    runtimePackages+=("$line")
done < <(grep "^lib" develop.packages.list | grep -v dev$ | grep -v bin$)

# 将数组拼接成字符串
function join_by {
  local d=${1-} f=${2-}
  if shift 2; then printf %s "$f" "${@/#/$d}"; fi
}

include=""
case $module in
    runtime)
        include=$(join_by , "${runtimePackages[@]}")
        ;;
    develop)
        include=$(join_by , "${developPackages[@]}")
        ;;
esac

# shellcheck disable=SC2001
echo "$include"|sed 's|,|\n|g' > "$module.include.list"


workdir=$(dirname "${BASH_SOURCE[0]}")

mmdebstrap \
        --customize-hook="ARCH=$arch MODULE=$module chroot \$1 /bin/bash < $workdir/hook.sh" \
        --customize-hook="ARCH=$arch MODULE=$module chroot \$1 /bin/bash < hook.sh" \
        --hook-dir=/usr/share/mmdebstrap/hooks/merged-usr \
        --components="main" \
        --variant=apt \
        --architectures="$arch" \
        --include="$include" \
        beige \
        "$module.tar" \
        https://pools.uniontech.com/deepin-beige

# 将tar包解压成目录
rm -rf "$module" || true
mkdir -p "$module/files"
tar -xvf "$module.tar" -C "$module/files" || true # 不知为何，解压到最后会报错但不影响使用
rm "$module.tar"